[theme]
primaryColor = "#FF9800"
backgroundColor = "#DDE3FF"           # Light bluish background
secondaryBackgroundColor = "#B3C4FF"  # Soft blue for sidebar
textColor = "#000000"                 # Black text for better readability
font = "monospace"
